### ISSUE TITLE
Nightly deployment certificate has expired

### ISSUE THREAD

**Issue by christian-brindley** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#107]
The wildcard certificate used for the nightly obdemo deployment has expired e.g. the certificate at

   https://obdemo.nightly.forgerock.financial/ig/openig/studio/

This is blocking remote consent among other things, because the RCS API backend does not trust IG.

**Comment by jorgesanchezperez** [comment]
Certificate renewed following the below steps:
- Run the pipeline [ForgeCloud/sbat-infra -> cert-renewal](https://g.codefresh.io/pipelines/edit/workflow?id=6149f2e1d3d6afff9fd9036a&pipeline=cert-renewal&projects=ForgeCloud%2Fsbat-infra&projectId=6026619964db840ccbb14863&rightbar=variables&context=github-bot) setting the `TARGET_ENVIRONMENT` pipeline parameter with the value of the namespace environment to renew the certificate (in that case `nightly`)
