### ISSUE TITLE
Investigate slow IG test: getTrustedDirectoryConfiguration_IGTestDirectoryEnabled

### ISSUE THREAD

**Issue by dbadham-fr** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#1103]
Test: com.forgerock.sapi.gateway.trusteddirectories.TrustedDirectoryServiceStaticTest#getTrustedDirectoryConfiguration_IGTestDirectoryEnabled

This test is taking ~20 seconds to run which is a large proportion of the ~24 second total time to run `mvn install` for the module.

**Comment by BohoCode** [comment]
Needs investigation to work out why this is

**Comment by dbadham-fr** [comment]
Fixed by #1393 

The URL equality check was taking a long time as, under the hood, the check is doing DNS lookups. #1393 fixes this issue by using URIs which perform an equals by checking the URI representations match.
