### ISSUE TITLE
Add JARM support to ReSignIdTokenFilter

### ISSUE THREAD

**Issue by dbadham-fr** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#1104]
`ReSignIdTokenFilter` was implemented to workaround an issue with id_token signing in AM, see issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/968

If the AM issue still exists when we support JARM, then we need to update the filter to support re-signing id_token inside the jwt response_mode, and the response jwt as well.

**Comment by BohoCode** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Development-625027a2231bd8001f38d79f/issues/SecureApiGateway/SecureApiGateway/1104?planning-poker) with Zenhub @dbadham-fr @jorgesanchezperez
