### ISSUE TITLE
Postman: create collection and environment for release v2.0.0 Blur to be run against relenv v2

### ISSUE THREAD

**Issue by jsanhc** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#1109]
As a customer I want to use postman to test the journeys against the release 2.0.0 so that I can be sure that all works properly.

- Duplicate the collection v1.0.0 to create the collection v2.0.0 release
    - Add the new journey Confirmation of Funds to the collection v2.0.0 release
    - Duplicate the environment v1.0.0 to create the environment for v2.0.0 release

**Comment by BohoCode** [comment]
Duplicate of #1166
