### ISSUE TITLE
Create IG route: /accounts/{AccountId}/balances

### ISSUE THREAD

**Issue by jorgesanchezperez** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#112]
### Description
The balances resource is used by an AISP to retrieve in bulk or single account balance information for a specific AccountId for that the PSU has authorised to access.
### Issues related
- https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/114
### Route Specifications
- **read/write API:** Account and Transaction
- **Specification link:** [GET /accounts/{AccountId}/balances v3.1.8](https://openbankinguk.github.io/read-write-api-site3/v3.1.8/resources-and-data-models/aisp/Balances.html#get-accounts-accountid-balances)
- **Endpoint:** /accounts/{AccountId}/balances
- **Method:** GET
- **API version spec:** [Balances v3.1.8](https://openbankinguk.github.io/read-write-api-site3/v3.1.8/resources-and-data-models/aisp/Balances.html)
- **API uri:** /rs/open-banking/v3.1.*/aisp/accounts/{AccountId}/balances
### Acceptance criteria
- [x] Functional tests passed in nightly environment
- [x] Functional tests passed in dev environment
- [x] Proper response expected by the spec
- [x] Errors expected match with the OBIE specs
- [x] Route documented
   - [x] Route source commented
   - [x] Add the route documentation to the wiki route section

**Comment by mariantiris** [comment]
Functionality implemented in: /securebanking-openbanking-demo/blob/master/config/7.0/obdemo-bank/ig/routes/routes-service/11-ob-account-access.json
