### ISSUE TITLE
Upgrade IG to version 2024.3.0

### ISSUE THREAD

**Issue by dbadham-fr** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#1159]
**Update** Issues identified in 2023.6.0 are going to be fixed in **2024.3.0**, upgrade to this version when it is released.

As part of the forgeops 7.3.0 upgrade, we attempted to upgrade IG to version 2023.6.0 but ran into some issues.

We found that version 2023.4.0 worked so upgraded to that instead https://github.com/SecureApiGateway/SecureApiGateway/issues/1154

It appears that there is some issue introduced in 2023.6.0, we have experienced a number of HTTP 503 Bad Gateway responses when IG is reverse proxying another system (such as RCS or AM).

In the logs we see an NPE in the vertx code
```
java.lang.NullPointerException: Cannot invoke \"io.netty.handler.codec.http2.Http2Stream.id()\" because \"stream\" is null
io.vertx.core.http.impl.VertxHttp2ConnectionHandler.writeData(VertxHttp2ConnectionHandler.java:227)
io.vertx.core.http.impl.VertxHttp2Stream.doWriteData(VertxHttp2Stream.java:225)
io.vertx.core.http.impl.Http2ClientConnection$Stream.doWriteData(Http2ClientConnection.java:275)
io.vertx.core.http.impl.VertxHttp2Stream.writeData(VertxHttp2Stream.java:208)
```

**Comment by BohoCode** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Development-625027a2231bd8001f38d79f/issues/SecureApiGateway/SecureApiGateway/1159?planning-poker) with Zenhub @dbadham-fr @jorgesanchezperez

**Comment by dbadham-fr** [comment]
Release candidate version is now available:

IG jar version: 2024.3.0-M2024-02.3
Docker image: gcr.io/forgerock-io/ig/pit1:2024.3.0-M2024-02.3
