### ISSUE TITLE
Create IG Route: /transactions

### ISSUE THREAD

**Issue by jorgesanchezperez** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#116]
### Description
The transactions resource is used by an AISP to retrieve the transactions for a specific AccountId or to retrieve the transactions in bulk for account(s) that the PSU has authorised to access.
### Issues related
- https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/114
### Route Specifications
- **read/write API:** Account and Transaction
- **Specification link:** [GET /transactions v3.1.8](https://openbankinguk.github.io/read-write-api-site3/v3.1.8/resources-and-data-models/aisp/Transactions.html#get-transactions)
- **Endpoint:** /transactions
- **Method:** GET
- **API version spec:** [Transactions v3.1.8](https://openbankinguk.github.io/read-write-api-site3/v3.1.8/resources-and-data-models/aisp/Transactions.html)
- **API uri:** /rs/open-banking/v3.1.*/aisp/transactions
### Acceptance criteria
- [x] Functional tests passed in nightly environment
- [x] Functional tests passed in dev environment
- [x] Proper response expected by the spec
- [x] Errors expected match with the OBIE specs
- [x] Route documented
   - [x] Route source commented
   - [x] Add the route documentation to the wiki route section

**Comment by mariantiris** [comment]
Functionality implemented in: /securebanking-openbanking-demo/blob/master/config/7.0/obdemo-bank/ig/routes/routes-service/12-ob-account-access-multiple-routes.json
