### ISSUE TITLE
Address issues raised in PR review: #314

### ISSUE THREAD

**Issue by dbadham-fr** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#1162]
A number of issues were raised in the following PR review: https://github.com/SecureApiGateway/secure-api-gateway-ob-uk/pull/314

The PR needed to be merged to unblock some other work.

Example issue:
ApiClientOrg in IDM is storing the organisations id in the name field.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHd5QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1348ce7da84dd93a44f65fed15ec5dfc3b0efbe7/image.png)

https://github.com/SecureApiGateway/secure-api-gateway-ob-uk/pull/314#discussion_r1121309808

**Comment by dbadham-fr** [comment]
This issue was introduced in PR:
https://github.com/SecureApiGateway/secure-api-gateway-ob-uk/pull/314

There are a number of issues raised in the review that we not addressed.

**Comment by jsanhc** [comment]
![Screenshot from 2023-10-18 16-51-24](https://github.com/SecureApiGateway/SecureApiGateway/assets/54277573/a54eb34e-4a78-45e8-8f4b-30b091678019)
