### ISSUE TITLE
Enhance functional tests to handle when rs.obie.validation.config.payments.requirePaymentContextCode is true is RS spring settings

### ISSUE THREAD

**Issue by BohoCode** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#1168]
### Feature Story (optional)

As an ASPSP wishing to enforce that payment submissions contain Risk objects with a valid PaymentCodeContext in I want the functional test to work against my system.

### Is your feature request related to a problem? Please describe.

I have a deployment in which the rs application.yml has rs.obie.validation.config.payments.requirePaymentContextCode set to true and most of the functional payment tests fail with the error;

```
{"Code":"400","Id":"2130f57459acb6aff5c5e74a8611a9a1",
"Message":"[Status: 400 Bad Request]",
"Errors":[
  {
    "ErrorCode":"UK.OBIE.Field.Invalid",
    "Message":"The 'OBRisk1.PaymentCodeContext' field must be set and be valid"
  }
]
}
```

### Describe the solution you'd like.

I would like the functional tests to pass

### Describe alternatives you've considered

none

**Comment by dbadham-fr** [comment]
Fixed by issue: https://github.com/SecureApiGateway/SecureApiGateway/issues/1170
