### ISSUE TITLE
Create IG Route: /accounts/{AccountId}/beneficiaries

### ISSUE THREAD

**Issue by jorgesanchezperez** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#117]
### Description
An AISP may retrieve the account beneficiaries information resource for a specific AccountId (which is retrieved in the call to GET /accounts).
### Issues related
- https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/114
### Route Specifications
- **read/write API:** Account and Transaction
- **Specification link:** [GET /accounts/{AccountId}/beneficiaries v3.1.8](https://openbankinguk.github.io/read-write-api-site3/v3.1.8/resources-and-data-models/aisp/Beneficiaries.html#get-accounts-accountid-beneficiaries)
- **Endpoint:** /accounts/{AccountId}/beneficiaries
- **Method:** GET
- **API version spec:** [Beneficiaries v3.1.8](https://openbankinguk.github.io/read-write-api-site3/v3.1.8/resources-and-data-models/aisp/Beneficiaries.html)
- **API uri:** /rs/open-banking/v3.1.*/aisp/accounts/{AccountId}/beneficiaries
### Acceptance criteria
- [x] Functional tests passed in nightly environment
- [x] Functional tests passed in dev environment
- [x] Proper response expected by the spec
- [x] Errors expected match with the OBIE specs
- [x] Route documented
   - [x] Route source commented
   - [x] Add the route documentation to the wiki route section

**Comment by mariantiris** [comment]
Functionality implemented in: /securebanking-openbanking-demo/blob/master/config/7.0/obdemo-bank/ig/routes/routes-service/11-ob-account-access.json
