### ISSUE TITLE
Publish functional test framework library

### ISSUE THREAD

**Issue by dbadham-fr** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#1174]
https://github.com/SecureApiGateway/SecureApiGateway/issues/1172 has restructured the functional tests repo, this allows us to publish a library. Customers can use this library to write their own test suite.

Tasks
- Use maven-publish gradle plugin to publish a jar for src/main
- Add SNAPSHOT versioning support to the project
  - Review changes need to release workflow
- Update github actions to publish SNAPSHOTs on PR merge to master
- Update github actions to publish release version when a release is done

**Comment by shaunharrisonFR** [comment]
Could this ticket be split out?
