### ISSUE TITLE
Consent Dialogs titles are misleading

### ISSUE THREAD

**Issue by BohoCode** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#1176]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzZWQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0ebe0f730e0032dd1960d11ae28b4a455941b91c/image.png)

As you can see, the title of the dialog informs the resource owner that they are setting up a standing order to "SAPIG Automating Testing". This is clearly incorrect.

**Comment by jsanhc** [comment]
Consents reviewed/fixed:
-  [x] Share Accounts: `Aligned with version` **[3.1.11](https://standards.openbanking.org.uk/customer-experience-guidelines/account-information-services/account-information-consent/v3-1-11/)**
<img src="https://github.com/SecureApiGateway/SecureApiGateway/assets/54277573/0fc092f3-a729-406e-a828-d92d4cf99b2a" width="300">

- [x] Domestic Payments: `Aligned with version` **[3.1.11](https://standards.openbanking.org.uk/customer-experience-guidelines/payment-initiation-services/single-domestic-payments-acc-selection-aspsp/v3-1-11/)**
<img src="https://github.com/SecureApiGateway/SecureApiGateway/assets/54277573/ae2f45de-0f2b-48a9-93c3-4004aa2890ab" width="300">

- [x] Domestic Schedules payments: `Aligned with version` **[3.1.11](https://standards.openbanking.org.uk/customer-experience-guidelines/payment-initiation-services/v3-1-11/)**
<img src="https://github.com/SecureApiGateway/SecureApiGateway/assets/54277573/74081741-1fc4-4f33-a227-cc9b9d3e8c71" width="300">

- [x] Domestic Standing Orders: `Aligned with version` **[3.1.11](https://standards.openbanking.org.uk/customer-experience-guidelines/payment-initiation-services/standing-orders/v3-1-11/)**
<img src="https://github.com/SecureApiGateway/SecureApiGateway/assets/54277573/3270d32d-6ea8-4d20-8d0f-d0c074ab6636" width="300">

- [x] International payments: `Aligned with version` **[3.1.11](https://standards.openbanking.org.uk/customer-experience-guidelines/payment-initiation-services/v3-1-11/)**
<img src="https://github.com/SecureApiGateway/SecureApiGateway/assets/54277573/2f137bdd-500f-4be3-b7d8-ba76f2ecd54b" width="300">

- [x] International Scheduled Payments: `Aligned with version` **[3.1.11](https://standards.openbanking.org.uk/customer-experience-guidelines/payment-initiation-services/v3-1-11/)**
<img src="https://github.com/SecureApiGateway/SecureApiGateway/assets/54277573/07be9a5d-c17e-4460-8d0b-c218b067f946" width="300">

- [x] International Standing Orders: `Aligned with version` **[3.1.11](https://standards.openbanking.org.uk/customer-experience-guidelines/payment-initiation-services/standing-orders/v3-1-11/)**
<img src="https://github.com/SecureApiGateway/SecureApiGateway/assets/54277573/8c6d2824-fb8e-414c-960c-52f0f722e0f6" width="300">

- [x] VRP payments: `Aligned with version` **[3.1.11](https://standards.openbanking.org.uk/customer-experience-guidelines/payment-initiation-services/v3-1-11/)**
<img src="https://github.com/SecureApiGateway/SecureApiGateway/assets/54277573/7aaaa493-7fcf-4b86-a8f3-1b79b58af743" width="300">

- [x] File Payments: `Aligned with version` **[3.1.11](https://standards.openbanking.org.uk/customer-experience-guidelines/payment-initiation-services/v3-1-11/)**
<img src="https://github.com/SecureApiGateway/SecureApiGateway/assets/54277573/c044e49d-ac67-424b-af7f-e7a750a3cc49" width="300">
