### ISSUE TITLE
Raise an alert when routes fail to load in the release environments

### ISSUE THREAD

**Issue by dbadham-fr** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#1187]
See example log:
https://console.cloud.google.com/logs/query;cursorTimestamp=2023-11-28T13:38:33.619886938Z;duration=PT1H;query=SEARCH%2528%22%60ob.aspsp.software.id%60%22%2529%0Atimestamp%3D%222023-11-28T13:38:33.619886938Z%22%0AinsertId%3D%2203q9f5wcvg3hwyto%22%0Atimestamp%3D%222023-11-28T13:38:33.619886938Z%22%0AinsertId%3D%2203q9f5wcvg3hwyto%22?project=sbat-dev

All routes must get loaded by IG in order for the deployment to behave correctly.

Create an alert which when IG logs: `An error occurred while reading the route defined in the file`

**Comment by dbadham-fr** [comment]
It would also be useful to have this alert in the dev environment too but only for the dev namespace. This issue has just been noticed in dev for the route protecting /authorize.

This will capture route configuration being broken when merging to master. We don't want alerts in each developers namespace, as route config will routinely get broken as part of development work.

**Comment by shaunharrisonFR** [comment]
We couldn't do this via terraform as its not possible to create custom alerts based on logs. 

For now I've manually created the alerts in GCP, which of course won't get deleted during the terraform destroy

You also can't script via bash or python to create these, they can only be created via a [management api](https://cloud.google.com/logging/docs/alerting/log-based-alerts#lba-by-api), where you have the requirements in a json package and then send it to the management api via a gcloud alpha command. 

Will leave this ticket for now, but if we find we need to look at the management api or another way of scripting comes available will re look into it
