### ISSUE TITLE
Create release charts to deploy FatJoe and deploy to ob-sandbox-v2

### ISSUE THREAD

**Issue by BohoCode** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#1195]
Deploy our FatJoe release to ob-sandbox-v2 ready to get FAPI 1.0 - Part 2 Advanced certification (with PAR and JARM)

**Comment by shaunharrisonFR** [comment]
Estimate may change depending on changes required, at this time it is an unknown

**Comment by shaunharrisonFR** [comment]
work completed in https://github.com/SecureApiGateway/SecureApiGateway/issues/1251
