### ISSUE TITLE
Update helm charts and kustomize manifests to work with kubernetes versions from 1.25→1.27

### ISSUE THREAD

**Issue by BohoCode** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#1196]
Prepare for newer versions of Kubernetes as v1.25 which we currently deploy on will be end of life by the time we need to release Gomez. We should update to v1.27.

**Comment by shaunharrisonFR** [comment]
Will need to review

- https://kubernetes.io/blog/2022/12/09/kubernetes-v1-26-release/
- https://kubernetes.io/blog/2023/04/11/kubernetes-v1-27-release/

And see what changes are required & deploy to devops cluster before changing the dev environment & upgrade relenvs

**Comment by shaunharrisonFR** [comment]
Devops env deployed correctly, will test on Devenvs on the 5th Dec

**Comment by shaunharrisonFR** [comment]
Devenvs working okay, will wait a day or two and update relenvs
