### ISSUE TITLE
Update helm charts and kustomize manifests to work with kubernetes versions from 1.27→1.28

### ISSUE THREAD

**Issue by BohoCode** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#1197]
v1.28 is not yet available in the Stable channel, but if it becomes available before we release Gomez we should update charts to work with v1.28 to give the Gomez release as long a life as possible.

**Comment by shaunharrisonFR** [comment]
Will need to review 

- https://kubernetes.io/blog/2023/08/15/kubernetes-v1-28-release/

And see what changes are required & deploy to devops cluster before changing the dev environment & upgrade relenvs
