### ISSUE TITLE
Create IG Route: /products

### ISSUE THREAD

**Issue by jorgesanchezperez** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#124]
### Description
The product resource is used by an AISP to retrieve the account product information for a specific AccountId.
The products resource is used by an AISP to retrieve the products for all authorised accounts linked to a specific account-request.
### Issues related
- https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/114
### Route Specifications
- **read/write API:** Account and Transaction
- **Specification link:** [GET /products v3.1.8](https://openbankinguk.github.io/read-write-api-site3/v3.1.8/resources-and-data-models/aisp/Products.html#get-products)
- **Endpoint:** /products
- **Method:** GET
- **API version spec:** [Products v3.1.8](https://openbankinguk.github.io/read-write-api-site3/v3.1.8/resources-and-data-models/aisp/Products)
- **API uri:** /rs/open-banking/v3.1.*/aisp/products
### Acceptance criteria
- [x] Functional tests passed in nightly environment
- [x] Functional tests passed in dev environment
- [x] Proper response expected by the spec
- [x] Errors expected match with the OBIE specs
- [x] Route documented
   - [x] Route source commented
   - [x] Add the route documentation to the wiki route section

**Comment by mariantiris** [comment]
Functionality implemented in: /securebanking-openbanking-demo/blob/master/config/7.0/obdemo-bank/ig/routes/routes-service/12-ob-account-access-multiple-routes.json
