### ISSUE TITLE
Create IG Route: /accounts/{AccountId}/parties

### ISSUE THREAD

**Issue by jorgesanchezperez** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#127]
### Description
The parties resource is used by an AISP to retrieve the details on the account owner(s)/holder(s) and operator(s) for a specific account identified by AccountId.
The party resource is used by an AISP to retrieve the details on the account owner/holder for a specific account identified by AccountId:
- In the case of a business, this will be the details of the business
- In the case of a joint account, this will be the party that has given authorisation to the AISP to view the account
### Issues related
- https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/114
### Route Specifications
- **read/write API:** Account and Transaction
- **Specification link:** [GET /accounts/{AccountId}/parties v3.1.8](https://openbankinguk.github.io/read-write-api-site3/v3.1.8/resources-and-data-models/aisp/Parties.html#get-accounts-accountid-parties)
- **Endpoint:** /accounts/{AccountId}/parties
- **Method:** GET
- **API version spec:** [Parties v3.1.8](https://openbankinguk.github.io/read-write-api-site3/v3.1.8/resources-and-data-models/aisp/Parties.html)
- **API uri:** /rs/open-banking/v3.1.*/aisp/accounts/{AccountId}/parties
### Acceptance criteria
- [x] Functional tests passed in nightly environment
- [x] Functional tests passed in dev environment
- [x] Proper response expected by the spec
- [x] Errors expected match with the OBIE specs
- [x] Route documented
   - [x] Route source commented
   - [x] Add the route documentation to the wiki route section

**Comment by mariantiris** [comment]
Functionality implemented in: /securebanking-openbanking-demo/blob/master/config/7.0/obdemo-bank/ig/routes/routes-service/11-ob-account-access.json
