### ISSUE TITLE
Create release actions for secure-api-gateway-core

### ISSUE THREAD

**Issue by dbadham-fr** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#1294]
Add in workflow to core repo for releasing the Core IG

**Comment by BohoCode** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Development-625027a2231bd8001f38d79f/issues/SecureApiGateway/SecureApiGateway/1294?planning-poker) with Zenhub @dbadham-fr

**Comment by BohoCode** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Development-625027a2231bd8001f38d79f/issues/SecureApiGateway/SecureApiGateway/1294?planning-poker) with Zenhub @shaunharrisonFR

**Comment by shaunharrisonFR** [comment]
This is being done within #1389
