### ISSUE TITLE
Deploy to nightly environment & run functional and DCR tests against nightly during PR / Merge actions in GitHub

### ISSUE THREAD

**Issue by shaunharrisonFR** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#1316]
We have Core being deployed and now has functional tests, meaning we should start pushing to nightly as well as the existing dev to ensure we aren't breaking anything in a FIDC deployment (cloud)

**Comment by shaunharrisonFR** [comment]
@BohoCode @dbadham-fr Anyone against this being done now we've got core & functional tests for core?

**Comment by dbadham-fr** [comment]
Sounds good

**Comment by shaunharrisonFR** [comment]
Work done, waiting to test
