### ISSUE TITLE
Investigate Ingress for Core

### ISSUE THREAD

**Issue by shaunharrisonFR** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#1323]
We currently have MTLS ingress protected by the OBWac ssl certs, which are generated via Open Banking.

Do we need to revise this when creating a 'core' deployment to fully strip OB out of the product

**Comment by dbadham-fr** [comment]
Good point, we need to generate a new certificate for the MTLS ingress to use. This cert needs to be issued by the Test Trusted Directory CA.

We also should update the following nginx configuration (which configures MTLS):
```
nginx.ingress.kubernetes.io/auth-tls-secret: $(NAMESPACE)/obri-ca
```
This configures MTLS to expect the client to send a cert signed by one of the CAs present in that secret, currently the secret contains the Open Banking Pre Production CA certs and the Test Trusted Directory CA cert, a new secret should be created which just contains the Test Trusted Directory CA cert.

**Comment by dbadham-fr** [comment]
After further discussion, we would like to support the OB Trusted Directory in SAPI-G core as it is simpler to configure and has more features than the Test Trusted Directory, see https://github.com/SecureApiGateway/SecureApiGateway/issues/1338
