### ISSUE TITLE
Configure nightly-core env

### ISSUE THREAD

**Issue by dbadham-fr** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#1336]
The nightly-core env will use the bravo realm of the `https://openam-sapig-nightly.forgeblocks.com/` tenant.

Platform config tasks:
- Update [sapig-overlay/core](https://github.com/SecureApiGateway/fr-platform-config/tree/master/sapig-overlay/core) to move realm specific config to the bravo realm
- Configure fr-config-manager to create the following objects in the bravo realm
  - users
  - OAuth2 agents

k8s config tasks:
- Create core-deployment-config for nightly
  - Set AM_REALM to bravo
  - Set USER_OBJECT to bravo_user
- nightly specific ingress configuration specifying the bravo realm in AM URLs

**Comment by shaunharrisonFR** [comment]
All of the above has been completed throughout various tickets throughout the week

Once the `oauth2-agents.json` issue is sorted (not a blocker but nice to have) we can spin up a nightly-core and see what is what
