### ISSUE TITLE
Investigate if typ header is incorrectly mandatory in detached jwt signature headers

### ISSUE THREAD

**Issue by BohoCode** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#1371]
A SAPIG user has reported that the detached jwt signatures required on the payment endpoints require a typ=JOSE header in the jwt. Both the JWS and the Open Banking specifications say the typ header is optional;

https://datatracker.ietf.org/doc/html/rfc7515#section-4.1.9
https://openbankinguk.github.io/read-write-api-site3/v3.1.10/profiles/read-write-data-api-profile.html#step-2-form-the-jose-header

**Comment by dbadham-fr** [comment]
The issue was a false positive, the actual issue the customer was experiencing was the same as: https://github.com/SecureApiGateway/SecureApiGateway/issues/1358

Closing this issue as https://github.com/SecureApiGateway/SecureApiGateway/issues/1358 has been fixed and released.
