### ISSUE TITLE
Generate v4.0 OB Datamodel

### ISSUE THREAD

**Issue by BohoCode** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#1440]

**Comment by BohoCode** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Development-625027a2231bd8001f38d79f/issues/SecureApiGateway/SecureApiGateway/1440?planning-poker) with Zenhub @dbadham-fr

**Comment by dbadham-fr** [comment]
v4 data model + controller interfaces have been generated and merged into the `ob-v4` branch.

The data model will likely need to be re-generated, as there are a number of bugs in the schema which we expect OBL to fix and release a patch.
