### ISSUE TITLE
Allow different tls certs to be used for core and test-trusted-directory

### ISSUE THREAD

**Issue by dbadham-fr** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#1508]
Currently the core deployment and test-trusted-directory deployment reference the same secret for terminating TLS (secret name `sslcert`)

This requires that the cert is either wildcarded i.e. `*.core-sandbox-v3.forgerock.financial` or that multiple subject alternative names are used.

Review this setup and document the certificate requirements / process to configure.

**Comment by shaunharrisonFR** [comment]
Need to document how we use kustomize within the deployment overlay to change the secret name using patch
