### ISSUE TITLE
Review k8s ingress annotations

### ISSUE THREAD

**Issue by dbadham-fr** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#1509]
Review all of the annotations configured in the k8s ingress.

https://github.com/SecureApiGateway/secure-api-gateway-releases/blob/master/core/kustomize/overlay/7.3.0/defaults/ingress.yaml#L7C5-L20C56

In particular, this annotation is configured incorrectly as invalid quote marks are being used. However, we need to understand the purpose of this annotation as the protocol we use to communicate with the backend services / pods is HTTP.
```
nginx.ingress.kubernetes.io/backend-protocol: “HTTPS"
```

**Comment by shaunharrisonFR** [comment]
I believe I added this when doing the http -> https redirect, believing at the time it was needed and being applied. The redirect is working so I'd guess we can just remove this out
