### ISSUE TITLE
Create temporary IG route to return RS discovery JSON document with already implemented endpoints in

### ISSUE THREAD

**Issue by BohoCode** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#200]
The format can be found at the existing RS discovery endpoint. See here;
[https://obdemo.dev.forgerock.financial/rs/open-banking/discovery](https://obdemo.dev.forgerock.financial/rs/open-banking/discovery)

**Comment by mariantiris** [comment]
test notification

**Comment by BohoCode** [comment]
@jorgesanchezperez  yo!
