### ISSUE TITLE
Statements file download not working

### ISSUE THREAD

**Issue by mariantiris** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#221]
The https://ig.domain/rs/open-banking/v3.1.8/aisp/accounts/{{AccountId}}/statements/{{StatementId}}/file endpoint is returning error when called.

Steps to reproduce the behaviour:

1.  Create an account access intent and authorize it for "ReadStatementsDetail"
2.  Access the endpoint mentioned above
3.  See error

**Expected behaviour**
The api should return unstructured data in binary (e.g., pdf, doc) or text (e.g., csv) formats. This will be specified in the Accept header by the AISP.

**Current behaviour**
The following error is returned:
`{
    "Code": "501",
    "Id": "41616a7f5dc1507616d152e30b14e28b",
    "Message": "[Status: 501 Not Implemented]",
    "Errors": {
        "ErrorCode": "UK.OBIE.UnexpectedError",
        "Message": "Internal error"
    }
}`

**Comment by jorgesanchezperez** [comment]
Closed: check implementations:
- https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-uk-rs/pull/71
- https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-demo/pull/106
