### ISSUE TITLE
Add all supported intent types in IG

### ISSUE THREAD

**Issue by mariantiris** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#232]
We need to add support in IG for all the different intent types in RepoConsent.groovy

- [x] ACCOUNT_ACCESS_CONSENT
- [x] PAYMENT_DOMESTIC_CONSENT
- [x] PAYMENT_DOMESTIC_SCHEDULED_CONSENT
- [x] PAYMENT_DOMESTIC_STANDING_ORDERS_CONSENT
- [x] PAYMENT_INTERNATIONAL_CONSENT
- [x] PAYMENT_INTERNATIONAL_SCHEDULED_CONSENT
- [x] PAYMENT_INTERNATIONAL_STANDING_ORDERS_CONSENT
- [x] PAYMENT_FILE_CONSENT
- [x] FUNDS_CONFIRMATION_CONSENT
- [x] DOMESTIC_VRP_PAYMENT_CONSENT

**Comment by jorgesanchezperez** [comment]
Fixed on: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/204
PR: https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-demo/pull/98
