### ISSUE TITLE
Scripted policy updates for GET requests on payments flows

### ISSUE THREAD

**Issue by mariantiris** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#246]
We need to add separation between POST requests validations and GET request validations on the payments flows. Currently the script performs validations for POST requests body. The same validations fail on GET requests because of the missing request body.

**Comment by andra-racovita** [comment]
PR: https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-uk-fidc-initializer/pull/66
