### ISSUE TITLE
Create IG Route for Domestic Scheduled Payment

### ISSUE THREAD

**Issue by BohoCode** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#249]
### Description
- [x] Create Route on Ig routes project [openbanking-demo routes](https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-demo/tree/master/config/7.0/obdemo-bank/ig/routes/routes-service)
- [x] Create if necessary specific groovy script to implement on IG the domestic scheduled payments.
- [x] Methods to support: GET, POST
- [x] Create the Submit Domestic Scheduled Payment route
- [x] Create the Get Domestic Scheduled Payment route
### Acceptance criteria
- [x] The route is deployed in Ig with no errors.
- [x] Proper response expected by the spec
- [x] Errors expected match with the OBIE specs
- [x] Route documented
   - [x] Route source commented
   - [x] Add the route documentation to the wiki route section

**Comment by jorgesanchezperez** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Development-625027a2231bd8001f38d79f/issues/SecureBankingAccessToolkit/SecureBankingAccessToolkit/249?planning-poker) with ZenHub @BohoCode
