### ISSUE TITLE
Remove the multiple environments endpoints from Allowed Audience Values from OAuth2 Provider when we have a CDR per namespace

### ISSUE THREAD

**Issue by andra-racovita** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#259]
### Feature Story (optional)

Related to issue: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/255

### Is your feature request related to a problem? Please describe.

We have to remove the multiple environments endpoints from Allowed Audience Values from OAuth2 Provider when we have a CDR per namespace.

So instead of this list:
`"allowedAudienceValues": [
      "https://obdemo.dev.forgerock.financial:443/am/oauth2/realms/root/realms/alpha/access_token",
      "https://obdemo.nightly.forgerock.financial:443/am/oauth2/realms/root/realms/alpha/access_token",
      "https://obdemo.andra-racovita.forgerock.financial:443/am/oauth2/realms/root/realms/alpha/access_token",
      "https://obdemo.mariantiris.forgerock.financial:443/am/oauth2/realms/root/realms/alpha/access_token",
      "https://obdemo.christian-brindley.forgerock.financial:443/am/oauth2/realms/root/realms/alpha/access_token",
      "https://obdemo.bohocode.forgerock.financial:443/am/oauth2/realms/root/realms/alpha/access_token",
      "https://obdemo.jorgesanchezperez.forgerock.financial:443/am/oauth2/realms/root/realms/alpha/access_token",
      "https://obdemo.joycegilding-forgerock.forgerock.financial:443/am/oauth2/realms/root/realms/alpha/access_token"
    ]`
we should have only:
`"allowedAudienceValues": [
      "https://obdemo.<env>.forgerock.financial:443/am/oauth2/realms/root/realms/alpha/access_token"
    ]`

### Describe the solution you'd like.

In pending...

### Describe alternatives you've considered

In pending...

**Comment by jorgesanchezperez** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Development-625027a2231bd8001f38d79f/issues/SecureBankingAccessToolkit/SecureBankingAccessToolkit/259?planning-poker) with Zenhub @BohoCode @dbadham-fr @frlaura-jianu @mariantiris

**Comment by BohoCode** [comment]
Now fixed
