### ISSUE TITLE
Detached signature validation fails on postman built signatures

### ISSUE THREAD

**Issue by mariantiris** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#264]
### Describe de bug

Current way of signing the detached signature in postman adds some additional claims to the JWT's body (iat, nbf, exp).

The detached signature payload must contain only the payment details in order to be rebuilt and validated in IG. We need to create a different postman implementation in order to avoid adding any additional claims to the JWT payload.

### Steps to reproduce the behaviour.

1. Create a payment consent and go to the payment sign and submit step
2. Send the request and observe the postman console logs from the pre-request script
3. Decode the JWT payload and notice the additional claims besides the payment body

### Expected behaviour

The JWT payload should only contain the payment details

### Current behaviour

The JWT contains some additional claims:

- iat
- exp
- nbf

**Comment by BohoCode** [comment]
Is this fixed now @mariantiris ?

**Comment by mariantiris** [comment]
This is fixed now by using a different library in the postman pre-request script: http://kjur.github.io/jsrsasign.

Steps to use the library:

1. Check if the postman environment already has a variable named **jsrsasign-js**
2. If the variable is not found in the environment, call http://kjur.github.io/jsrsasign/jsrsasign-latest-all-min.js to download the library source code and save it in the **jsrsasign-js** variable. Otherwise, if the variable is already present this step is skipped.
3. Load the cryptographic library downloaded in the previous steps into postman: `eval(pm.environment.get("jsrsasign-js"));`
4. Build the JSON header and payload that we need, and then use the ob-seal private key to build the signed JWT using the loaded cryptographic library: `KJUR.jws.JWS.sign(null, header, data, privateKey);`
