### ISSUE TITLE
[Sprint-action]: Unblock VPN issues to improve debugging options

### ISSUE THREAD

**Issue by jorgesanchezperez** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#269]
### Describe the action

Currently the collaborators in the project have some issues with the VPN Access
Better debugging options. 
Blocked by the VPN access issues so far.

### Acceptance criteria (optional)

- Unblocked VPN (or disable access by VPN)

**Comment by BohoCode** [comment]
We have a VPN solution now.
