### ISSUE TITLE
Configure each developer namespace to use it's own instance of the CDK

### ISSUE THREAD

**Issue by BohoCode** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#276]
Each developer configmap, as defined in the [securebanking-openbanking-uk-gateway](https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-uk-gateway) repository, where there is a kustomize overlay defined for each developer in the following directory;
`/kustomize/overlay/7.0/obdemo-bank/<developer-name>`

The value that will need to be set in each developer environment is the 
IDENTITY_PLATFORM_FQDN value, which is currently set in the securebanking-openbanking-initializer project in the main config map helm template found in the following directory;
`/_infra/helm/securebanking-openbanking-uk-fidc-initializer/templates`

Adding an entry in the local overlay file will override that default value. The value of the new entry in each kustomize overlay will need to be;

IDENTITY_PLATFORM_FQDN: iam.<dev-namespace>.forgerock.financial

So, for example, in this file;
https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-demo/blob/master/kustomize/overlay/7.0/obdemo-bank/bohocode/configmap.yaml

We would see the entry;
IDENTITY_PLATFORM_FQDN: iam.bohocode.forgerock.financial

**Note**
The [overlay for the nightly environment](https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-demo/blob/master/kustomize/overlay/7.0/obdemo-bank/nightly/configmap.yaml) would stay the same as it's configured to use an instance of identity cloud and not the CDK.

**Comment by BohoCode** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Development-625027a2231bd8001f38d79f/issues/SecureBankingAccessToolkit/SecureBankingAccessToolkit/276?planning-poker) with ZenHub @joycegilding-forgerock

**Comment by joycegilding-forgerock** [comment]
Code changes made but we have since uncovered that the securebanking-openbanking-uk-fidc-initializer has PSU test users created. This has some tests to fail when the developer's name are removed from the NAMESPACES.md if they are not removed from securebanking-openbanking-uk-fidc-initializer. A separate project is to be created for creating PSU test data to decouple initializer from testing.

**Comment by joycegilding-forgerock** [comment]
Each developer will need to add their own  IDENTITY_PLATFORM_FQDN in securebanking-openbanking-demo repository when they are ready to move to their own CDK namespace. Currently this has been tested on joycegilding-forgerock and it works.

**Comment by BohoCode** [comment]
This now works. We have more to do to switch over and build a nightly pipeline - but for now, we can run a dev env per developer.
