### ISSUE TITLE
Verify if Domestic scheduled payment API has been implemented on RS backend

### ISSUE THREAD

**Issue by jorgesanchezperez** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#283]
### Description
- [x] Verify the implementation of domestic scheduled payment API on RS backend
Spec: https://openbankinguk.github.io/read-write-api-site3/v3.1.8/resources-and-data-models/pisp/domestic-scheduled-payments.html
Repository: [securebanking-openbanking-uk-rs](https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-uk-rs)
- [x] Verify if the Domestic scheduled payment APIs are in the RS Discovery

### Acceptance criteria
- [x] The Domestic scheduled payment APIs are implemented.

**Comment by jorgesanchezperez** [comment]
## Verification info
- Is implemented from `3.1.8` to `v3.0`
- The version `3.1.8` extends `3.1.7` extends `3.1.6` extends `3.1.5` (implementation)
- Interfaces [here](https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-uk-rs/tree/master/securebanking-openbanking-uk-rs-obie-api)
- Implementation [here](https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-uk-rs/tree/master/securebanking-openbanking-uk-rs-simulator-server)

**Comment by jorgesanchezperez** [comment]
`x-account-id` is mandatory and defined in the controller interface, needs to be check where we need to sent that header.

**Comment by andra-racovita** [comment]
`x-ob-account-id` header is used in the creation of the domestic scheduled payment. So, we need to save the account Id in the debtor account to be able to send it in the header.

**Comment by andra-racovita** [comment]
Verify why the Create Domestic Scheduled Payment URL is not listed in the RS discovery.
