### ISSUE TITLE
Move terraform state file from Openbanking to sbat-dev

### ISSUE THREAD

**Issue by joycegilding-forgerock** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#289]
Move terraform state file from Openbanking to sbat-dev

**Comment by jorgesanchezperez** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Development-625027a2231bd8001f38d79f/issues/SecureBankingAccessToolkit/SecureBankingAccessToolkit/289?planning-poker) with Zenhub @BohoCode @dbadham-fr @frlaura-jianu @mariantiris @shaunharrisonFR

**Comment by shaunharrisonFR** [comment]
From sprint planning , need to consider the user account we are using for if it has the correct permissions to read, create and delete files in the new bucket
