### ISSUE TITLE
Encrypt financial data in IDM

### ISSUE THREAD

**Issue by christian-brindley** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#30]
## Story

As a customer I want to encrypt payment and account data so that I can protect my customer data and comply with Identity Cloud acceptable use policy.

## Acceptance criteria

- Financial data payload for account access and payment intents are encrypted in IDM

**Comment by BohoCode** [comment]
If IDM is responsible for doing this encryption, then the payload will not be viewable by any of the banks internal systems. I think it should be down to the RS gateway that the bank would need to implement to do this encryption before storing.
