### ISSUE TITLE
Delete unused source (groovy scripts)

### ISSUE THREAD

**Issue by jorgesanchezperez** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#307]
### Components

IG

### Describe the issue

**Comment from `Dom Reed`**
The following scripts don’t seem to be used in any routes. Could someone confirm if they are needed still? And either let me know what they are for or remove them from the repo to avoid confusion?
[BasicAuthResourceServerFilter.groovy](https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-demo/blob/master/config/7.0/obdemo-bank/ig/scripts/groovy/BasicAuthResourceServerFilter.groovy)
[CheckAccountAccess.groovy](https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-demo/blob/master/config/7.0/obdemo-bank/ig/scripts/groovy/CheckAccountAccess.groovy)
[RCSBuildResponseJwt.groovy](https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-demo/blob/master/config/7.0/obdemo-bank/ig/scripts/groovy/RCSBuildResponseJwt.groovy)  (seems to relate to a route 21 which I can’t find)
[RCSGetConsent.groovy](https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-demo/blob/master/config/7.0/obdemo-bank/ig/scripts/groovy/RCSGetConsent.groovy)  (seems to relate to a route 20 which I can’t find)
[RCSSendConsent.groovy](https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-demo/blob/master/config/7.0/obdemo-bank/ig/scripts/groovy/RCSSendConsent.groovy)  (seems to relate to a route 21 which I can’t find)

### User Story (optional)

As the developer, I want to have clean the repository of unused source so that avoid confusions.

### Acceptance criteria (optional)

- [x] No unused source in the repository
- [x] All functional tests pass
- [x] All postman tests pass

### Delete
- [BasicAuthResourceServerFilter.groovy](https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-demo/blob/master/config/7.0/obdemo-bank/ig/scripts/groovy/BasicAuthResourceServerFilter.groovy)
- [CheckAccountAccess.groovy](https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-demo/blob/master/config/7.0/obdemo-bank/ig/scripts/groovy/CheckAccountAccess.groovy)
- [RCSBuildResponseJwt.groovy](https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-demo/blob/master/config/7.0/obdemo-bank/ig/scripts/groovy/RCSBuildResponseJwt.groovy)
- [RCSGetConsent.groovy](https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-demo/blob/master/config/7.0/obdemo-bank/ig/scripts/groovy/RCSGetConsent.groovy)
- [RCSSendConsent.groovy](https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-demo/blob/master/config/7.0/obdemo-bank/ig/scripts/groovy/RCSSendConsent.groovy)

**Comment by jorgesanchezperez** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Development-625027a2231bd8001f38d79f/issues/SecureBankingAccessToolkit/SecureBankingAccessToolkit/307?planning-poker) with ZenHub @andra-racovita @BohoCode @dbadham-fr @joycegilding-forgerock @mariantiris

**Comment by mariantiris** [comment]
Unused sources have been deleted. The only thing to note is that [BasicAuthResourceServerFilter.groovy](https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-demo/blob/master/config/7.0/obdemo-bank/ig/scripts/groovy/BasicAuthResourceServerFilter.groovy) is used and has been kept. IT is not used in a route but it's used in admin.json

**Comment by mariantiris** [comment]
Closing issue. Functional and postman tests are all green.
