### ISSUE TITLE
Update forgeops version to release 7.1.2

### ISSUE THREAD

**Issue by joycegilding-forgerock** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#339]
We are using release 7.1.0 in our Sbat development environment. The 7.1.0 release is using the api version ' networking.k8s.io/v1beta1 ' which will be deprecated when we update the GKE version to v1.22 

This will need to be updated to the latest version which is currently 7.1.2 which does not use the deprecated api version.

**Comment by dreed12** [comment]
FYI, 7.2 is due out at the end of June

**Comment by dbadham-fr** [comment]
We have upgraded to use forgeops 7.1.2 to unblock the k8s 1.22 work and this upgrade was trivial.

#437 has been raised to upgrade to 7.2.0
