### ISSUE TITLE
OpenBanking demo postman collection - provisioning collection does not assign admin privileges for IDM

### ISSUE THREAD

**Issue by christian-brindley** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#34]
The Postman collection for configuring the Identity Cloud tenant does not assign the right privileges to the service account for managing IDM objects.

Need to update postman collection to assign openidm-admin role to user service_account.ig

**Comment by jterryfr** [comment]
Is this still relevant? Looking at the initialiser it seems that we already have the admin role
https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-uk-fidc-initializer/blob/5dae2a2646a2a6413f86b3e60c3d46efed6c14d9/am/serviceaccount.go#L35
