### ISSUE TITLE
Add Standing Order Consent case in the Repo Consent Script

### ISSUE THREAD

**Issue by andra-racovita** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#340]
### Description
- Add implementation to support Domestic Standing Order Consent in the [60-internal-repo route](https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-demo/blob/master/config/7.0/obdemo-bank/ig/routes/routes-service/60-internal-repo.json) :
   -  [x] Verify, and update the [buildPatchRequest function ](https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-demo/blob/master/config/7.0/obdemo-bank/ig/scripts/groovy/RepoConsent.groovy#L10) if needed
   - [x] Verify, and update the [convertIDMResponse function](https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-demo/blob/master/config/7.0/obdemo-bank/ig/scripts/groovy/RepoConsent.groovy#L102)  if needed
### Acceptance criteria
- [x] A `Domestic Standing Order Consent` is patched in the IDM with the right data
- [x] The response of the GET `Domestic standing order consent` is modeled in the right way

**Comment by jorgesanchezperez** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Development-625027a2231bd8001f38d79f/issues/SecureBankingAccessToolkit/SecureBankingAccessToolkit/340?planning-poker) with ZenHub @andra-racovita
