### ISSUE TITLE
Initialiser templating

### ISSUE THREAD

**Issue by jorgesanchezperez** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#343]
### Introduction

This feature allows the customer use their own values to populate the sbat configuration to customer Forgerock cloud platform.

### User Story

As a customer, I want to set my own values in the platform initialiser so that a can populate my own SBAT values to cloud platform.

### Product requirements (optional)

- The initialiser needs to be templating
- The initialiser needs to be running from a docker image

### Scope

- To populate configuration to cloud platform.

### Acceptance Criteria

- [ ] something

**Comment by BohoCode** [comment]
All issues are now closed. Closing this epic.
