### ISSUE TITLE
Create functional tests coverage: International payment funds confirmation

### ISSUE THREAD

**Issue by jorgesanchezperez** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#380]
### Description
- [x] Add the proper functional tests to cover international payment funds confirmation
### Acceptance criteria
- [x] All current postman tests pass.
- [x] The `International payment funds confirmation` request tests pass.

**Comment by jorgesanchezperez** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Development-625027a2231bd8001f38d79f/issues/SecureBankingAccessToolkit/SecureBankingAccessToolkit/380?planning-poker) with ZenHub @andra-racovita @mariantiris

**Comment by andra-racovita** [comment]
Implemented in PR: https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-uk-functional-tests/pull/48
