### ISSUE TITLE
IG - add funds confirmation route

### ISSUE THREAD

**Issue by christian-brindley** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#41]
The IG configuration included with openbanking-demo deployment does not include a route for funds confirmation. 

We should add a new route for `domestic-payment-consents/.*/funds-confirmation` as per PSD2 accelerators.

**Comment by jorgesanchezperez** [comment]
The correct issue to do that task is: https://github.com/securebankingaccesstoolkit/securebankingaccesstoolkit/issues/297
