### ISSUE TITLE
Functional test coverage: international scheduled payment funds confirmation

### ISSUE THREAD

**Issue by jorgesanchezperez** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#419]
### Description
- [x] Add the proper functional tests to cover international scheduled payment funds confirmation
### Acceptance criteria
- [x] All current postman tests pass.
- [x] The `International scheduled payment funds confirmation` request tests pass.

**Comment by jorgesanchezperez** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Development-625027a2231bd8001f38d79f/issues/SecureBankingAccessToolkit/SecureBankingAccessToolkit/419?planning-poker) with ZenHub @frlaura-jianu @mariantiris

**Comment by jorgesanchezperez** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Development-625027a2231bd8001f38d79f/issues/SecureBankingAccessToolkit/SecureBankingAccessToolkit/419?planning-poker) with ZenHub @andra-racovita

**Comment by andra-racovita** [comment]
Implemented in PR: https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-uk-functional-tests/pull/48
