### ISSUE TITLE
Implement OB v3.1.10 in the RS mock bank

### ISSUE THREAD

**Issue by BohoCode** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#424]
Depends of #440

**Comment by dbadham-fr** [comment]
For VRP in 3.1.10 there are breaking changes, see https://wikis.forgerock.org/confluence/pages/viewpage.action?pageId=125863306

There are also bugs in OBIE spec for VRP 3.1.8 (missing idempotency key header which can lead to multiple payments being made in error) and 3.1.9. 

Therefore we will only support VRP 3.1.10+ in SBAT, this means that we do not need to worry about handling the breaking changes at this point, we will generate the VRP data model as 3.1.10.

There are no known breaking changes in the other APIs (account, payments) etc, so we can support 3.1.8, 3.1.9 and 3.1.10 for those APIs.
