### ISSUE TITLE
Postman: Review existing tests, Update existing tests if necessary

### ISSUE THREAD

**Issue by jorgesanchezperez** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#435]
# Description
- Review existing tests to ensure that all works properly
- Update existing postman tests
- Add new ones if necessary
# Acceptance criteria
- [x] All postman tests pass

**Comment by jorgesanchezperez** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Development-625027a2231bd8001f38d79f/issues/SecureBankingAccessToolkit/SecureBankingAccessToolkit/435?planning-poker) with ZenHub @andra-racovita @frlaura-jianu @mariantiris

**Comment by frlaura-jianu** [comment]
There was an issue with the Domestic Standing Orders flow.
