### ISSUE TITLE
Upgrade IDM objects to support the calculated response elements

### ISSUE THREAD

**Issue by jorgesanchezperez** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#439]
# Description
- Upgrade the IDM objects to support the calculated response elements
# Initial Approach (investigation if is possible to do it)
- Add a charges object in IDM to be relationship with Intent objects

**Comment by mariantiris** [comment]
Implemented the solution as array of objects instead of separate charge object with 1..n relationships.
