### ISSUE TITLE
Implement OB v3.1.9 in the RS mock bank

### ISSUE THREAD

**Issue by jorgesanchezperez** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#440]

**Comment by dbadham-fr** [comment]
Discussed this with @BohoCode, as we want to support 3.1.10 as soon as possible then we will generate the data model using the 3.1.10 schemas only.

As part of this issue we will only be adding the controller support for 3.1.9.

**Comment by jorgesanchezperez** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Development-625027a2231bd8001f38d79f/issues/SecureBankingAccessToolkit/SecureBankingAccessToolkit/440?planning-poker) with ZenHub @BohoCode @dbadham-fr @frlaura-jianu @mariantiris

**Comment by jorgesanchezperez** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Development-625027a2231bd8001f38d79f/issues/SecureBankingAccessToolkit/SecureBankingAccessToolkit/440?planning-poker) with ZenHub @andra-racovita

**Comment by dbadham-fr** [comment]
3.1.9 data model classes and RS mock bank APIs have been added.

Functional tests have been updated to include 3.1.9 tests for the existing set of supported routes, the tests use identical logic as 3.1.8 for these routes (but hit the 3.1.9 end points).

The codefresh functional tests pipeline has been updated to run 3.1.8 and 3.1.9 tests.
