### ISSUE TITLE
Initializer Helmcharts calling non-existent executable

### ISSUE THREAD

**Issue by frsuner** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#445]
### Describe the bug

https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-uk-fidc-initializer/blob/master/_infra/helm/securebanking-openbanking-uk-fidc-initializer/templates/cronjob.yaml

States ./setup instead of ./initialize . When container is ran it runs with the error ./setup not found . ./setup was deprecated and golang now creates ./initialize . 

### Steps to reproduce the behaviour.

1. modifying helm chart to use on minikube. 
2. added explicit image as there is no pipeline and changed pull policy
3. added hostnameAliases to deal with local DNS issues. 
4. run helm install 

### Expected behaviour

Container start up and completion

### Current behaviour

CrashLoop with a bash error of ./setup not found.

**Comment by BohoCode** [comment]
Invalid. The right helm chart calls the correct executable. SHould have been using this instead:
https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-uk-fidc-initializer/blob/master/_infra/helm/securebanking-openbanking-uk-iam-initializer/templates/cronjob.yaml
