### ISSUE TITLE
Run functional tests when environment is built at start of day

### ISSUE THREAD

**Issue by dbadham-fr** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#511]
The SBAT master-dev cluster is rebuilt everyday, after the cluster is built we would like to know that it is functioning correctly.

Run the SBAT functional tests codefresh pipeline after the initialise-cluster pipeline.

Add a notification mechanism to the functional tests pipeline so that a notification is sent if the tests fail.

**Comment by jorgesanchezperez** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Development-625027a2231bd8001f38d79f/issues/SecureBankingAccessToolkit/SecureBankingAccessToolkit/511?planning-poker) with Zenhub @BohoCode @dbadham-fr @mariantiris @frlaura-jianu

**Comment by dbadham-fr** [comment]
The functional test pipeline has a step which will send a slack notification if the functional tests fail and  pipeline variable NOTIFY_SLACK == 'true'. By default, the NOTIFY_SLACK variable is set to false for the pipeline, this is to reduce spam when people are manually running the tests.

The initialise-cluster pipeline will call the functional test pipeline as its final step, with the notifications enabled.
