### ISSUE TITLE
UK-gateway: Update `ModifyPaymentIntentResponse` groovy script

### ISSUE THREAD

**Issue by jorgesanchezperez** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#519]
## Description
Update `ModifyPaymentIntentResponse` groovy script to support then new changes introduced in managed object.
- [Here](https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-uk-gateway/blob/master/config/7.0/obdemo-bank/ig/scripts/groovy/ModifyPaymentIntentResponse.groovy)

**Comment by dbadham-fr** [comment]
This filter can be removed, as all it was doing was removing AccountId from the OB response object. We have achieved this via the schema refactor, so the filter/groovy script are now redundant.
