### ISSUE TITLE
Generate File payment reports and support LBG differences

### ISSUE THREAD

**Issue by matt-wills** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#52]
## Story

As an Open Banking customer
I want the RS simulator to support the generation of file payment reports
so that a customer can access file payment reports successfully

## Acceptance criteria
- File payment reports are generated for all supported versions (see `PaymentReportFile1Service`).

## Tasks
- [ ] Determine if report functionality is definitely required.
- [ ] Investigate LBG differences (including to other file payment endpoints).

### Release Notes

Affected App: securebanking-rs-simulator

## Notes
For further information, refer to:
* https://docs.google.com/document/d/14j920MUjnxqdj34yG-Kut0SfHXrLmCTud-pHWDcDR88/edit?ts=60911287
* https://drive.google.com/drive/u/0/folders/1xOAytgYdqNLsQn-HoTibGfCgWYVvWprB

**Comment by BohoCode** [comment]
No customer's asking for this currently. No customers actually use the simulator. Closing.
