### ISSUE TITLE
RS backend: Update backoffice APIs

### ISSUE THREAD

**Issue by jorgesanchezperez** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#521]
## Description
Update backoffice APIs to use `OB object JSON-based`.
- [x] Calculate elements #509 
- [ ] Funds confirmation

**Comment by jorgesanchezperez** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Development-625027a2231bd8001f38d79f/issues/SecureBankingAccessToolkit/SecureBankingAccessToolkit/521?planning-poker) with Zenhub @BohoCode @dbadham-fr @frlaura-jianu @mariantiris

**Comment by dbadham-fr** [comment]
The Calculate Elements backoffice APIs were updated to use the OB object in: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/509

The funds confirmation API does not have the intent as a param, it takes an accountId and an amount. Therefore nothing to updated.
