### ISSUE TITLE
DCR: Review and potentially fix SSA/QWac validation

### ISSUE THREAD

**Issue by jorgesanchezperez** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#524]
## Description
Currently to validate the SSA against the TPP QWac certificate we use from DN components the `organisation identifier (OI)` (last part) to check if match with SSA claim `org_id`.
This validation seems wrong when the TPP certificate OI value doesn't contains the Organisation ID as part of `OI` value. The validation process expect `PSDGB-FFA-5f563e89742b2800145c7da1` or `PSDGB-OB-Unknown0015800001041REAAY` (issue by OB) as `OI` but we detect in some cases that the register is rejected because the TPP certificate have an `OI` value as PSDGB-FCA-123456` where the last part is the PSP identifier and not is the organisation Id.

From documentation (@See references)
**ETSI**
```shell
The organizationIdentifier "PSDPL-PFSA-1234567890" means a certificate issued to a PSP where
the authorization number is 1234567890, authorization was granted by the Polish Financial
Supervision Authority (identifier after second hyphen-minus is decided by Polish numbering
system). Other examples can include use of non-alphanumeric characters such as "PSDBE-NBB1234.567.890" and "PSDFI-FINFSA-1234567-8" and "PSDMT-MFSA-A 12345" (note space
character after "A"). 
```
**Open Banking**
```text
2.3ORGANISATIONALIDENTIFIER STATEMENTAs specified in [REF 1]
The PSD2 Authorization Number, or  other identifier recognized by the NCA, shall be placed in organizationIdentifier attribute of the Subject Distinguished Name field in the certificate.

The organizationIdentifier "PSDGB-OB-Unknown0015800001041ReAAI" means a certificate issued to a TPPwhere the authorization number is Unknown0015800001041ReAAI, authorizationwas granted by UK Open Banking (identifier PSDGB-OB). 
Other examples can include use of non-alphanumeric characters such as "PSDBE-NBB-1234.567.890", "PSDFI-FINFSA-1234567-8" and "PSDMT-MFSA-A 12345" (note space character after "A").

After  consultations  between  European  Banking  Authority  (EBA)  and  ETSI  it  wasfound  that  there  are  institutions which can request PSD2 certificates but have no authorization number. If the authorization number was not issued by the NCA, then another registration identifier recognized by the NCA is used from  those defined in the standard ETSI EN/TS 319 412-1
```

## References
- [ETSI specification for QWAC and QSEAL certificates](https://www.etsi.org/deliver/etsi_ts/119400_119499/119495/01.02.01_60/ts_119495v010201p.pdf) page 12.
- [eIDAS PSD2 Certificate Signing Request Profiles](https://openbanking.atlassian.net/wiki/download/attachments/1150124033/OpenSSL%20eIDAS%20PSD2%20Certificate%20Signing%20Request%20Profiles%20Issue%202_1.pdf?version=1&modificationDate=1567524981238&cacheVersion=1&api=v2) pages 5 and 6

## Solution
Update the validation process to check the `OI` field against the `SSA` `registration_id` field instead of the `org_id`

## Code
**SSA**
```json
{
.....
"organisation_competent_authority_claims": {
    "authority_id": "FCAGBR",
    "registration_id": "123456",
......
}
```
```json
{
...
"organisation_competent_authority_claims": {
    "authority_id": "OBGBR",
    "registration_id": "Unknown0015800001041REAAY",
...
}
```
**QWAC**
DN Component `2.5.4.97` `OI` `PSDGB-OB-Unknown0015800001041REAAY` or `PSDGB-OB-123456`
## Extras
**Comment from @christian-brindley**
To fix this, I believe we should be checking the certificate `organizationalIdentifier` field against the `SSA` `registration_id` field instead of the `org_id` field. This would actually resolve the whole issue of having to remove `Unknown` from the certificate identifier, as this is included in the `registration_id` field in the `SSA`. The OB spec is pretty confusing, but judging by the `Customer` situation, it seems we are not doing it right at the moment.
Not sure what we are doing in the sandbox as a service checks?

**Comment by dbadham-fr** [comment]
I've been discussing this issue with @BohoCode and we have designed an alternative solution to this issue.

Verifying fields in the cert vs ssa is error prone due to having to support OB issued certs and EIDAS certs. There is very little concrete information in the OBIE spec on how to implement this validation.

Even if we were to find a method to do this verification, it does not prove that the cert used for mTLS is currently mapped to the software statement. The only way we can think to verify this is by querying the `software_jwks_endpoint` in the software statement and checking if the cert is in the JWKS.

The way that we check if the cert exists in the JWKS is by comparing the x5c value (the X509 Certificate Chain), with the certificate available in the `ssl-client-cert` header (added by nginx). Both OB and nginx state that only the certificate will be present in this field, there will be no certificate chain.

We believe this is the strongest validation check that we can do to ensure that the mTLS cert is mapped to the TPP's software statement.

**Comment by dbadham-fr** [comment]
Support for IG issued test certificates has been implemented.

Both OB and IG certs will be validated against a JWKS as part of DCR.

Added a configuration property security.allowIgIssuedTestCerts to control whether the route accepts the test certs or not. Configured this property to true for the dev/config/config.json and false for prod/config/config.json
