### ISSUE TITLE
Rollback PR https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-uk-gateway/pull/176

### ISSUE THREAD

**Issue by jorgesanchezperez** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#525]
# Description
A temporary fix has been introduced waiting to implement the solution #515 to meanwhile make it compatible with the current implemented solution of [RS backend: Update all payments submission response to add calculated elements values](https://github.com/securebankingaccesstoolkit/securebankingaccesstoolkit/issues/488)

The fix has been introduced because some functionalities expected in the intent response from IG repo the field `data` and in RS to deserialise the object into an OB object is expected the root field `Data`. To make it compatible with the current functionalities and at the same time compatible with the solution [RS backend: Update all payments submission response to add calculated elements values](https://github.com/securebankingaccesstoolkit/securebankingaccesstoolkit/issues/488) the root field `data` has been duplicated to have `Data` too. This duplication needs to be deleted in the future.

## Temporary fix
- Added `Data` field in the response object to be compatible with the expected object by RS backend, it means that now the `data/Data` fields are duplicated.
- Groovy script with the temporary fix: https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-uk-gateway/blob/master/config/7.1.0/securebanking/ig/scripts/groovy/RepoConsent.groovy
- Lines commented with: `// TODO make it compatible with RS`
This temporary fix needs to be deleted when the solution #515 has been done.

## Tasks
- [ ] Delete the temporary fix introduce in the [PR-176](https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-uk-gateway/pull/176) to make it compatible with the RS latests changes
## Acceptance criteria
- [ ] All tests passed

**Comment by BohoCode** [comment]
Can we make this a subtask of #515 then??

**Comment by dbadham-fr** [comment]
> Can we make this a subtask of #515 then??

It is

**Comment by dbadham-fr** [comment]
Fixed in PR:
https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-uk-gateway/pull/188

Instead of rolling back, we have made the RepoConsent return the OBIntentObject
