### ISSUE TITLE
RS backend: Check calculate elements for international Standing Order Consent

### ISSUE THREAD

**Issue by jorgesanchezperez** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#528]
## Description
Check implementation of calculate elements to ensure that International Standing order calculate elements are supported, if not will be necessary make that implementation.

**Comment by jorgesanchezperez** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Development-625027a2231bd8001f38d79f/issues/SecureBankingAccessToolkit/SecureBankingAccessToolkit/528?planning-poker) with Zenhub @frlaura-jianu @mariantiris

**Comment by mariantiris** [comment]
Calculate elements controller is implemented for international standing orders.
