### ISSUE TITLE
Create method to return File Payment consents with only mandatory fields

### ISSUE THREAD

**Issue by jorgesanchezperez** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#559]
### Description
Create methods in [securebanking-openbanking-uk-obie-datamodel](https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-uk/tree/master/securebanking-openbanking-uk-obie-datamodel) to initialize objects only with the mandatory fields according to the [File Payment Consents - v3.1.8 Documentation](https://openbankinguk.github.io/read-write-api-site3/v3.1.8/resources-and-data-models/pisp/file-payment-consents.html)

**Comment by frlaura-jianu** [comment]
Heads up for fileHash logic - TBD
