### ISSUE TITLE
Run fapi compliance test as part of nightly deployment pipeline

### ISSUE THREAD

**Issue by BohoCode** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#613]
Run the FAPI compliance suite as part of the daily cron based deployments. It's possible to build a docker container of the FAPI compliance suite following the information [here](https://gitlab.com/openid/conformance-suite/-/wikis/home).

Loose guess at the tasks needed to achieve this;

- [ ] Create a Java Dynamic Client Registration client library. This can be used by a FAPI test data initialiser and by the Functional test library
- [ ] Develop a pipeline that will 
  - [x] initialise an SBAT env with FAPI test data (create two dynamic client registrations using OB Certs and SSA), 
  - [ ] Run the FAPI conformance test initialised with required OAuth2 client info.

## More info
Docker image runs the entire web app that is available on the oauth2 fapi compliance page (see [here](https://www.certification.openid.net))

There is a dynamic client registration conformance tool published by open banking that might offer some help;
https://openbanking.atlassian.net/wiki/spaces/DZ/pages/1193869584/Dynamic+Client+Registration+Conformance

**Comment by dbadham-fr** [comment]
Created 2 new Software Statements in Open Banking Directory to facilitate this testing:
- [fapi-compliance-1](https://github.com/OpenBankingUK/conformance-dcr): EfuiKIJ0FhNXpydbk5QSkw
- [fapi-compliance-2](https://manager.openbankingtest.org.uk/participants/PSD2/0015800001041REAAY/software-statements/CO7SNfOjhR8FaCSPvbEn8A): CO7SNfOjhR8FaCSPvbEn8A

**Comment by dbadham-fr** [comment]
Forked the OB conformance-dcr repo into here: https://github.com/SecureBankingAccessToolkit/conformance-dcr

Added a [SBAT-README.MD](https://github.com/SecureBankingAccessToolkit/conformance-dcr/blob/sbat-master/SBAT-README.MD) which documents SBAT customisations and development workflow.

The gist of the development workflow is as follows:

- sbat-master branch contains sbat customisations
   - Feature branches should be taken from this branch
   - PR flow should merge changes back to sbat-master
     - **Ensure the base repo for PRs is our fork and not the upstream**
- master branch is a read only mirror of the upstream master branch
- changes from the upstream can be synced to master and then merged into sbat-master as required

**Comment by dbadham-fr** [comment]
New pipeline added [fapi-dynamic-client-registration pipeline ](https://g.codefresh.io/pipelines/edit/new/builds?id=635a631afb98d04d1a27d27f&pipeline=fapi-dynamic-client-registration&projects=ForgeCloud%2Fsbat-infra&projectId=6026619964db840ccbb14863&filter=page:1)

This pipeline will do DCRs for the fapi-compliance-1/2 SSAs, the pipeline is current pointing at my env but this can be changed by overriding the WELLKNOWN_ENDPOINT variable.

The certificates/keys are stored in CF shared configuration as an encrypted secret. The format is the PEM on a single line, all line breaks must be converted to \n chars.

For example here is the FAPI_2_OB_WAC_CERT value (this is a public cert):
```
-----BEGIN CERTIFICATE-----\nMIIGWDCCBUCgAwIBAgIEWcaWtTANBgkqhkiG9w0BAQsFADBTMQswCQYDVQQGEwJH\nQjEUMBIGA1UEChMLT3BlbkJhbmtpbmcxLjAsBgNVBAMTJU9wZW5CYW5raW5nIFBy\nZS1Qcm9kdWN0aW9uIElzc3VpbmcgQ0EwHhcNMjIxMDI2MDk0MjA1WhcNMjMxMTI2\nMTAxMjA1WjBzMQswCQYDVQQGEwJHQjEaMBgGA1UEChMRRk9SR0VST0NLIExJTUlU\nRUQxKzApBgNVBGETIlBTREdCLU9CLVVua25vd24wMDE1ODAwMDAxMDQxUkVBQVkx\nGzAZBgNVBAMTEjAwMTU4MDAwMDEwNDFSRUFBWTCCASIwDQYJKoZIhvcNAQEBBQAD\nggEPADCCAQoCggEBANX967KVUS/6TnMrHPBkB28v2I1rimZq5XFZLdctqercVTfa\n8e7aiWNIwSeplZyuCtd8CWUxq+exbHp9xF1/wZdFkP5jP9TtdVmrlw8dFuqBGAtd\n0hTzTyVOykhQcO1sJU3uiiCroCVI9jqsWwgm7dDLkOjLoHLA93qLGbq1U8gLuRas\nQNbS0lipsgAB3fUxxMTNHpMMF59Zs9ICfMIFPBV6aGx5FKZYjzfRqOuEhJFhImrc\n9XkVX3bt/2k/tpzfnApJuZOc1Osxg3g6sI4pjUqIMAHiv6PXudokMS54czhMqPQd\nbsVcX3DMi3m7GQkvsadjt34ag4tCg1EJsqaL/R0CAwEAAaOCAxIwggMOMA4GA1Ud\nDwEB/wQEAwIHgDB4BgNVHREEcTBvgiVtYXRscy5ycy5hc3BzcC5vYi5mb3JnZXJv\nY2suZmluYW5jaWFsgiVtYXRscy5hcy5hc3BzcC5vYi5mb3JnZXJvY2suZmluYW5j\naWFsgh9ycy5hc3BzcC5vYi5mb3JnZXJvY2suZmluYW5jaWFsMIGRBggrBgEFBQcB\nAwSBhDCBgTATBgYEAI5GAQYwCQYHBACORgEGAzBqBgYEAIGYJwIwYDA5MBEGBwQA\ngZgnAQEMBlBTUF9BUzARBgcEAIGYJwECDAZQU1BfUEkwEQYHBACBmCcBAwwGUFNQ\nX0FJDBtGaW5hbmNpYWwgQ29uZHVjdCBBdXRob3JpdHkMBkdCLUZDQTAgBgNVHSUB\nAf8EFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwgeAGA1UdIASB2DCB1TCB0gYLKwYB\nBAGodYEGAWQwgcIwKgYIKwYBBQUHAgEWHmh0dHA6Ly9vYi50cnVzdGlzLmNvbS9w\nb2xpY2llczCBkwYIKwYBBQUHAgIwgYYMgYNVc2Ugb2YgdGhpcyBDZXJ0aWZpY2F0\nZSBjb25zdGl0dXRlcyBhY2NlcHRhbmNlIG9mIHRoZSBPcGVuQmFua2luZyBSb290\nIENBIENlcnRpZmljYXRpb24gUG9saWNpZXMgYW5kIENlcnRpZmljYXRlIFByYWN0\naWNlIFN0YXRlbWVudDBtBggrBgEFBQcBAQRhMF8wJgYIKwYBBQUHMAGGGmh0dHA6\nLy9vYi50cnVzdGlzLmNvbS9vY3NwMDUGCCsGAQUFBzAChilodHRwOi8vb2IudHJ1\nc3Rpcy5jb20vb2JfcHBfaXNzdWluZ2NhLmNydDA6BgNVHR8EMzAxMC+gLaArhilo\ndHRwOi8vb2IudHJ1c3Rpcy5jb20vb2JfcHBfaXNzdWluZ2NhLmNybDAfBgNVHSME\nGDAWgBRQc5HGIXLTd/T+ABIGgVx5eW4/UDAdBgNVHQ4EFgQUcei/KnLzndsJUBo/\n6ybUUNLEOMgwDQYJKoZIhvcNAQELBQADggEBAEBkcM/aRRoC2w2zSEwHPmqCNHwN\nklLAi9yBIo3JmlLFTOmIAUcAQ0QGGLOFLp1AgfQbib/UDnxan/kjJZf7vIEixWrB\npOw7rR9llkp0yVGgehWGx8O1rsJ/KXfJkh9ZCDbraqFv7T8y43FfBuKqeMAwu9uT\nWbc+EhauXHvaRm6r4mGs9L/YRaNJYkxTYo3+KbXnhCWU1UtgcM5NEVc1CobLqAk0\noidEXjZEkfYvUI9wEdbGUkkemJjGQHUEB1HPxa+NLdnrh90zYZRNF8T3fC0wwoX0\nM3QBDjz/zEzqPhk/mnLN7o/JvjMFqJkMxbBAfAO1sCbMenPs+sI2W6CKfCg=\n-----END CERTIFICATE-----
```

**Comment by dbadham-fr** [comment]
The FAPI compliance test suite requires manual intervention in order to do the psu authentication. Therefore it is not feasible to fully automate this test.

Instead we have automated running the DCR compliance suite (and worked on fixing issues reported), and creating a pipeline which can setup the fapi-compliance-1/2 registrations in an environment (in order to speed up setting up an environment to launch the fapi suite).
