### ISSUE TITLE
DCR verify registration request JWT signature in IG

### ISSUE THREAD

**Issue by dbadham-fr** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#624]
The DCR request sent to IG is a signed JWT, we are currently not validating the signature of this JWT, see:
https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-uk-gateway/blob/9aba9eb9f864f6e6a650f1ce47a5cbe1186ae85d/config/7.1.0/securebanking/ig/scripts/groovy/ProcessRegistration.groovy#L61

As a note, the JWT is not passed on to AM, only the body (which we modify). Therefore it is our responsibility to ensure this is validated.

OB spec: https://openbankinguk.github.io/dcr-docs-pub/v3.2/dynamic-client-registration.html#obclientregistrationrequest1

Tasks
- [x] Implement JWT signature validation
- [x] Add kid (key id) for the OB Seal used by Postman
- [x] Configure kid correctly for fapi-compliance-1/2 software statements used by FAPI / DCR conformance testing

**Comment by BohoCode** [comment]
Thinking about this a bit more.... 

I wonder if it would make sense for IG to do the validation of the SSA (where ever it is issued from) and then re-sign the SSA contents and then provide the SSA signed by IG (using the OBSeal in OB case), and then pass that on to AM? Then AM would do all the usual SSA field validation etc?

This way, if a customer was protecting custom APIs using their own directory things would still change and AM would _always_ just need to be configured to trust the IG signed SSA?

Even if the OB issued SSA was RFC-7591 compliant, I guess AM only checks the validity of the signing certificate. It won't be checking that the certificate used to sign the SSA is valid via a jwks_uri, so it will not be doing all the necessary checks for SSAs issued by the OB Directories.

So, the above approach means any ecosystem specific SSA checks would only concern IG. 

This approach might of course have knock on effects that I haven't thought through....

**Comment by BohoCode** [comment]
I guess the returned SSA in the registration request would then be signed by us, which would be odd for TPPs?

**Comment by dbadham-fr** [comment]
On a more general note, this issue concerns validating the OB DCR JWT https://openbankinguk.github.io/dcr-docs-pub/v3.2/dynamic-client-registration.html#obclientregistrationrequest1 , which wraps the SSA (in the software_statement claim).

We have implemented logic to validate the SSA (see [SSAVerifier](https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-uk-gateway/blob/master/config/7.1.0/securebanking/ig/scripts/groovy/SSAVerifier.groovy)) but we do not have logic to validate the OB DCR JWT.

As mentioned above, ideally we don't to have the SSAVerifier filter as the onus is on us to get it implemented correctly and maintain it which is something that AM can do.

**Comment by jorgesanchezperez** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Development-625027a2231bd8001f38d79f/issues/SecureBankingAccessToolkit/SecureBankingAccessToolkit/624?planning-poker) with Zenhub @BohoCode @dbadham-fr @frlaura-jianu @mariantiris
