### ISSUE TITLE
DCR Failure to get client_credentials access token: Subject Identifier must not be null

### ISSUE THREAD

**Issue by dbadham-fr** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#626]
For certain flows, we are experiencing issues getting client_credentials access tokens.

The following error response is received:
```
{"Code":"400","Id":"bf8b2ba1f3a85e9ea7c59505e52c7bd8","Message":"[Status: 400 Bad Request]","Errors":{"ErrorCode":"UK.OBIE.Field.Invalid","Message":"Bad req
uest [invalid_client] [Subject Identifier must not be null.]"}}   
```

This issue has been observed when running the DCR tool to create users, example log:
https://g.codefresh.io/build/6360ef2f3b250dcda6bb3f5f?step=create_dcr&tab=output&logs=terminal

**Comment by dbadham-fr** [comment]
AM exception trace (truncated):
```
Caused by: org.forgerock.oauth2.core.exceptions.InvalidClientException: Subject Identifier must not be null.
	at org.forgerock.openam.oauth2.token.OpenIdConnectTokenStore.createOpenIDToken(OpenIdConnectTokenStore.java:243)
	at org.forgerock.openidconnect.OpenIDTokenIssuer.lambda$issueToken$0(OpenIDTokenIssuer.java:75)
```

**Comment by dbadham-fr** [comment]
Turning on debug logging in AM reveals this:
```
{"timestamp":"2022-11-01T10:04:58.040Z","level":"DEBUG","thread":"http-nio-8081-exec-2","mdc":{"transactionId":"43ddb7f6c3d5788c7ee122a9b752636e"},"logger":"org.forgerock.openam.
oauth2.OpenAMClientRegistration","message":"Must configure sector identifier uri when multiple redirect uris are specified.","context":"default"}
```

Corresponding code: https://stash.forgerock.org/projects/OPENAM/repos/openam/browse/openam-oauth2/src/main/java/org/forgerock/openam/oauth2/OpenAMClientRegistration.java#1398-1418

The above code is called as part of validating the subject, as part of this routine: https://stash.forgerock.org/projects/OPENAM/repos/openam/browse/openam-oauth2/src/main/java/org/forgerock/openam/oauth2/token/OpenIdConnectTokenStore.java#243-268

Recently a change in the environment was made to fix a bug where if the subject_type was not specified in the DCR, then it was default to public, this has been fixed to enforce that the subject_type is pairwise.

**Comment by BohoCode** [comment]
Ah, yes! Of course!

**Comment by dbadham-fr** [comment]
The issue in codefresh is that we are configuring multiple redirect uris as part of the DCR. The fix for now is to only configure a single redirect uri.

Discussed this with @BohoCode , and have decided that supporting multiple redirect uris is not necessary at the current time.

**Comment by BohoCode** [comment]
This is because it is unlikely that any single application will need multiple callback URIs. If this issue crops up when a customer is using SBAT we can look into how to automate the sector identifier or even if that is possible.

**Comment by dbadham-fr** [comment]
https://github.com/SecureApiGateway/SecureApiGateway/issues/1178 has been raised to investigate supporting this combination.

After testing with our fapi-conformance-1 OAuth2.0 client, we have noticed that this is using multiple redirect_uris and pairwise subject_type. 
This is not having issues as all of the redirect_uris have the same host, AM will use this hostname when determining the `subId` to use, the issue only occurs when the redirect_uris are **not all** on the same domain.

This OAuth2.0 client registers the following `redirect_uris`: 
```
https://www.certification.openid.net/test/a/forgerock-sbat-dev/callback
https://www.certification.openid.net/test/b/forgerock-sbat-dev/callback
```
This client is able to achieve FAPI conformance.

The issue in this ticket relates to our automated testing software statement which supports the following redirect_uris which are on different domains:
```
https://postman-echo.com/get
https://www.google.co.uk
```

**Comment by dbadham-fr** [comment]
Tested configuring the `sector_identifier_uri` in the DCR request, this works as expected and our automated testing TPP is able to get pairwise subIds using multiple redirect_uris which are on different domains.

Documentation here: https://github.com/SecureApiGateway/SecureApiGateway/wiki/Using-Pairwise-Pseudonymous-Identifiers
