### ISSUE TITLE
IG: Add Domestic VRP Payment consent PATCH/GET case in the repo consent script to store the debtorAccount in the intent object.

### ISSUE THREAD

**Issue by jorgesanchezperez** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#635]
### Description
Patch and Get the debtor account object related with the intent `domesticVrpPaymentIntent` for RCS backend.
- Add implementation to support Domestic VRP payment Consent in the [60-internal-repo route](https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-demo/blob/master/config/7.0/obdemo-bank/ig/routes/routes-service/60-internal-repo.json) :
   -  [ ] Verify, and update the [buildPatchRequest function ](https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-demo/blob/master/config/7.0/obdemo-bank/ig/scripts/groovy/RepoConsent.groovy#L10) if needed
   - [ ] Verify, and update the [convertIDMResponse function](https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-demo/blob/master/config/7.0/obdemo-bank/ig/scripts/groovy/RepoConsent.groovy#L102)  if needed
### Acceptance criteria
- [ ] A `domesticVrpPaymentIntent` is patched in the IDM with the right data
- [ ] The response of the GET `Domestic VRP payment consent` is modeled in the right way

**Comment by mariantiris** [comment]
There seems to be generic implementation for payments that covers the implementation for VRP as well. Closing with no changes implemented.
