### ISSUE TITLE
IG - Implement 3.1.6 account access and domestic payments APIs

### ISSUE THREAD

**Issue by BohoCode** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#71]
## Story

As a team, we would like to get two user story journey's working completely to prove system architecture. Those two journeys are the account access journey and the domenstic payments journey.

Endpoints for the following resources will need to be implemented;
POST /domestic-payment-consents
GET /domestic-payment-consents/{ConsentId}
GET /domestic-payment-consents/{ConsentId}/funds-confirmation

POST /domestic-payments
GET /domestic-payments/{DomesticPaymentId}
GET /domestic-payments/{DomesticPaymentId}/payment-details

## Tasks
- [x] Analyse current IG routes
- [x] Api's version diff

**Comment by jorgesanchezperez** [comment]
### Current IG routes
| endpoint |  IG route | IG file |
| --- | --- | --- |
| POST /domestic-payment-consents | /rs/openbanking/v3.1/domestic-payment-consents | 10-ob-payment-consent.json |
| GET /domestic-payment-consents/{ConsentId} | N/A | |
| GET /domestic-payment-consents/{ConsentId}/funds-confirmation | N/A | |
| POST /domestic-payments | /rs/openbanking/v3.1.*/domestic-payments | 12-ob-payment-submission |
| GET /domestic-payments/{DomesticPaymentId} | N/A | |
| GET /domestic-payments/{DomesticPaymentId}/payment-details | N/A| |

**Comment by jorgesanchezperez** [comment]
### [Domestic payments API](https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-uk-rs/tree/master/securebanking-openbanking-uk-rs-obie-api/src/main/java/com/forgerock/securebanking/openbanking/uk/rs/api/obie/payment) version Diff
| version | Objects | Headers | extend | compared |
| --- | --- | --- | --- | --- |
| 3.0 | **Request**:<br>OBWriteDomestic1<br>**Response**:<br>OBWriteDomesticResponse1 | N/A | N/A | N/A |
| 3.1 | **Request**:<br>OBWriteDomestic2<br>**Response**:<br>OBWriteDomesticResponse2 | N/A | N/A | 3.0 |
| 3.1.1 | N/A | N/A | 3.1 | N/A |
| 3.1.2 | N/A | N/A | 3.1.1 | N/A |
| 3.1.3 | **Request**:<br>OBWriteDomestic2<br>**Response**:<br>OBWriteDomesticResponse3 |  +`x-fapi-auth-date`<br> - `x-fapi-customer-last-logged-time` | N/A | 3.1.2 |
| 3.1.4 | **Request**:<br>OBWriteDomestic2<br>**Response**:<br>OBWriteDomesticResponse4 |  +`x-read-refund-account` | N/A | 3.1.3 |
| 3.1.5 | **Request**:<br>OBWriteDomestic2<br>**Response**:<br>OBWriteDomesticResponse5 |  N/A | N/A | 3.1.4 |
| 3.1.6 | N/A | N/A | 3.1.5 | N/A |
| 3.1.7 | N/A | N/A | 3.1.6 | N/A |
| 3.1.8 | pending | pending | pending | pending |

**Comment by jorgesanchezperez** [comment]
- Follow on https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/90
