### ISSUE TITLE
Implement Github Actions for PRs

### ISSUE THREAD

**Issue by jterryfr** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#89]
Implement github action for sbat services to deploy PRs into developer environments and ensure that `sbat-gcr-develop` tags images based on the github hashes from master.

The Github action should create a docker container and  push to `sbat-gcr-develop` tagged as `pr-$number` where `$number` is the pr number supplied by github.
It should trigger the service-build pipeline in codefresh supplying the github actor, PR number and PR branch. 

We need our `sbat-gcr-release` to publish stable images only - not simply when something is merged to master. right now master doesn't necessarily mean stable. `sbat-gcr-release` will contain unstable dev images.

- [x] IG
- [x] UI
- [x] rs
- [x] rcs
- [x] config server
- [x] Functional tests

**Comment by jorgesanchezperez** [comment]
Tags for builded images:
- from **master**
   - latest
   - commit hash (10characters)
- From **release publish**
   - latest
   - the tag supplied by github related with the release (ex. 1.4.5 or v1.4.5)
